version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sambandha_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://sambandha_db_owner:npg_YRX4EbdZ9tmP@ep-lucky-dream-a17cojlf-pooler.ap-southeast-1.aws.neon.tech/sambandha_db?sslmode=require
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: